import { AttacksEntity } from "../attacks/attacks.entity";
import { LoottablesEntity } from "../loottables/loottables.entity";
import { MissionsEntity } from "../missions/missions.entity";
import { RacesEntity } from "../races/races.entity";
import { AffinityEntity } from "../affinity/affinity.entity";
import { ArmorEntity } from "../armor/armor.entity";
import { WeaponEntity } from "../weapon/weapon.entity";
import { HakiTypesEntity } from "../haki_types/hakiTypes.entity";
import { DevilFruitEntity } from "../devil_fruit/devilFruit.entity";
import { NpcInventoryEntity } from "../npc_inventory/npcInventory.entity";
import { PlayableCharacterJournalEntity } from "../playable_character_journal/playableCharacterJournal.entity";
export interface NpcEntity {
  id: string;
  name: string;
  biography: string;
  idRace: string;
  strength: string;
  dexterity: string;
  defense: string;
  aim: string;
  vision: string;
  speed: string;
  handcraft: string;
  agility: string;
  charisma: string;
  wisdom: string;
  affinityId: string;
  chroniclerStatus: string;
  imageReference: string;
  bossImageReference?: string;
  armorId?: string;
  weaponId?: string;
  hakiLevel?: string;
  hakiType?: string;
  devilFruitId?: string;
  health: string;
  maxHealth: string;
  attacks?: AttacksEntity[];
  loottables?: LoottablesEntity[];
  missions?: MissionsEntity[];
  races?: RacesEntity;
  affinity?: AffinityEntity;
  armor?: ArmorEntity;
  weapon?: WeaponEntity;
  hakiTypes?: HakiTypesEntity;
  devilFruit?: DevilFruitEntity;
  npcInventory?: NpcInventoryEntity[];
  playableCharacterJournal?: PlayableCharacterJournalEntity[];
}
