import { weapon_rarity, weapon_weapon_type } from "../../enums";
import { InventoryWeaponEntity } from "../inventory_weapon/inventoryWeapon.entity";
import { NpcEntity } from "../npc/npc.entity";
import { ElementsEntity } from "../elements/elements.entity";
import { SkillUsageEntity } from "../skill_usage/skillUsage.entity";
import { TilesEntity } from "../tiles/tiles.entity";
import { ObjectsEntity } from "../objects/objects.entity";
export interface WeaponEntity {
  id: string;
  name: string;
  elementId?: string;
  damagePointsLvl1: string;
  damagePointsLvl2: string;
  damagePointsLvl3: string;
  damagePointsLvl4: string;
  damagePointsLvl5: string;
  upgradeItemId: string;
  upgradeCostLvl2: string;
  upgradeCostLvl3: string;
  upgradeCostLvl4: string;
  upgradeCostLvl5: string;
  rarity: weapon_rarity;
  durability: string;
  durabilityMax: string;
  chipping?: string;
  ammo?: string;
  weaponType: weapon_weapon_type;
  locationId?: string;
  skillUsage?: string;
  diceNeeded?: string;
  found?: string;
  priceSell: string;
  priceBuy: string;
  description: string;
  image?: string;
  inventoryWeapon?: InventoryWeaponEntity[];
  npc?: NpcEntity[];
  elements?: ElementsEntity;
  skillUsageWeaponSkillUsageToskillUsage?: SkillUsageEntity;
  tiles?: TilesEntity;
  objects?: ObjectsEntity;
}
