import { AttacksEntity } from "../attacks/attacks.entity";
import { InventoryEntity } from "../inventory/inventory.entity";
import { InventoryMagicEntity } from "../inventory_magic/inventoryMagic.entity";
import { MissionJournalEntity } from "../mission_journal/missionJournal.entity";
import { UsersEntity } from "../users/users.entity";
import { RacesEntity } from "../races/races.entity";
import { AffinityEntity } from "../affinity/affinity.entity";
import { InventoryArmorEntity } from "../inventory_armor/inventoryArmor.entity";
import { InventoryWeaponEntity } from "../inventory_weapon/inventoryWeapon.entity";
import { HakiTypesEntity } from "../haki_types/hakiTypes.entity";
import { DevilFruitEntity } from "../devil_fruit/devilFruit.entity";
import { PlayableCharacterJournalEntity } from "../playable_character_journal/playableCharacterJournal.entity";

export interface PlayableCharacterEntity {
  id?: string;
  userId: string;
  name: string;
  biography?: string;
  idRace: string;
  positiveCharacteristic_1?: string;
  positiveCharacteristic_2?: string;
  positiveCharacteristic_3?: string;
  negativeCharacteristic_1?: string;
  negativeCharacteristic_2?: string;
  strength: string;
  dexterity: string;
  defense: string;
  aim: string;
  vision: string;
  speed: string;
  handcraft: string;
  agility: string;
  charisma: string;
  wisdom: string;
  affinityId: string;
  chroniclerStatus: string;
  imageReference?: string;
  armorId?: string;
  weaponId?: string;
  hakiLevel?: string;
  hakiTypeId?: string;
  devilFruitId?: string;
  devilFruitAwakening?: string;
  money?: string;
  health?: string;
  maxHealth?: string;
  activeMaxHealth?: string;
  attacks?: AttacksEntity[];
  inventory?: InventoryEntity[];
  inventoryArmorInventoryArmorIdUserToplayableCharacter?: InventoryArmorEntity[];
  inventoryMagic?: InventoryMagicEntity[];
  inventoryWeaponInventoryWeaponIdUserToplayableCharacter?: InventoryWeaponEntity[];
  missionJournal?: MissionJournalEntity[];
  users?: UsersEntity;
  races?: RacesEntity;
  affinity?: AffinityEntity;
  inventoryArmorPlayableCharacterArmorIdToinventoryArmor?: InventoryArmorEntity;
  inventoryWeaponPlayableCharacterWeaponIdToinventoryWeapon?: InventoryWeaponEntity;
  hakiTypes?: HakiTypesEntity;
  devilFruit?: DevilFruitEntity;
  playableCharacterJournal?: PlayableCharacterJournalEntity[];
}
