export enum attacks_attack_type {
  PLAYER2NPC = "PLAYER2NPC",
  PLAYER2MONSTER = "PLAYER2MONSTER",
  PLAYER2PLAYER = "PLAYER2PLAYER",
  NPC2PLAYER = "NPC2PLAYER",
  NPC2NPC = "NPC2NPC",
  NPC2MONSTER = "NPC2MONSTER",
  MONSTER2PLAYER = "MONSTER2PLAYER",
  MONSTER2NPC = "MONSTER2NPC",
  MONSTER2MONSTER = "MONSTER2MONSTER",
}
