import { objects_rarity } from "../../enums";
import { ArmorEntity } from "../armor/armor.entity";
import { InventoryEntity } from "../inventory/inventory.entity";
import { LoottablesEntity } from "../loottables/loottables.entity";
import { NpcInventoryEntity } from "../npc_inventory/npcInventory.entity";
import { ElementsEntity } from "../elements/elements.entity";
import { SkillUsageEntity } from "../skill_usage/skillUsage.entity";
import { TilesEntity } from "../tiles/tiles.entity";
import { SpellsEntity } from "../spells/spells.entity";
import { WeaponEntity } from "../weapon/weapon.entity";
export interface ObjectsEntity {
  id: string;
  name: string;
  elementId?: string;
  rarity: objects_rarity;
  skillUsageId?: string;
  diceNeeded?: string;
  locationId?: string;
  description: string;
  priceSell: string;
  priceBuy: string;
  armor?: ArmorEntity[];
  inventory?: InventoryEntity[];
  loottables?: LoottablesEntity[];
  npcInventory?: NpcInventoryEntity[];
  elements?: ElementsEntity;
  skillUsage?: SkillUsageEntity;
  tiles?: TilesEntity;
  spells?: SpellsEntity[];
  weapon?: WeaponEntity[];
}
